export const TOGGLE_SIDER_COLLAPSE = "TOGGLE_SIDER_COLLAPSE";

export const authTypes = {
    SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
    SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
    
    SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
    SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE"
};

export const ticketTypes = {
    SEARCH_TICKETS_SUCCESS: "SEARCH_TICKETS_SUCCESS",
    SEARCH_TICKETS_FAILURE: "SEARCH_TICKETS_FAILURE",

    SEARCH_TICKETS_PER_PAGE_SUCCESS: "SEARCH_TICKETS_PER_PAGE_SUCCESS",
    SEARCH_TICKETS_PER_PAGE_FAILURE: "SEARCH_TICKETS_PER_PAGE_FAILURE",

    GET_TICKET_DETAIL_SUCCESS: "GET_TICKET_DETAIL_SUCCESS",
    GET_TICKET_DETAIL_FAILURE: "GET_TICKET_DETAIL_FAILURE",

    GET_USERS_FROM_FRESHDESK_SUCCESS: "GET_USERS_FROM_FRESHDESK_SUCCESS",
    GET_USERS_FROM_FRESHDESK_FAILURE: "GET_USERS_FROM_FRESHDESK_FAILURE",

    GET_USERS_FROM_LOCALSTORAGE_SUCCESS: "GET_USERS_FROM_LOCALSTORAGE_SUCCESS",
    GET_USERS_FROM_LOCALSTORAGE_FAILURE: "GET_USERS_FROM_LOCALSTORAGE_FAILURE",

    SET_CURRENT_CATEGORY_SUCCESS: "SET_CURRENT_CATEGORY_SUCCESS",
    SET_CURRENT_CATEGORY_FAILURE: "SET_CURRENT_CATEGORY_FAILURE",

    GET_TICKET_TOTAL_BY_TAG: "GET_TICKET_TOTAL_BY_TAG",
    GET_TICKET_TOTAL_BY_DEFAULT: "GET_TICKET_TOTAL_BY_DEFAULT",

    SET_QUERY_UPDATED_AT: "SET_QUERY_UPDATED_AT"
};